name: Bug report
description: Report an issue/bug with the bot
title: "[Bug] ISSUE TITLE HERE"
labels: [bug]
body:
  - type: textarea
    id: bug-desc
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the behavior
      description: A clear and concise guide to recreate the bug.
      placeholder: Tell us how to reproduce
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What was suppose to happen
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        If applicable, add screenshots to help explain your problem.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
